/* Daway Pharmacy Hub JS */
document.addEventListener('DOMContentLoaded',()=>{initCharts();initInventorySteppers();initFilterTabs();initMedicineSearch();initModals();initMap();});

function initCharts(){if(!window.Chart)return;document.querySelectorAll('[data-ph-chart]').forEach(c=>{const t=c.dataset.phChart,l=JSON.parse(c.dataset.phLabels||'[]'),d=JSON.parse(c.dataset.phData||'[]'),colors=JSON.parse(c.dataset.phColors||'[]'),ctx=c.getContext('2d');let cfg={};if(t==='bar')cfg={type:'bar',data:{labels:l,datasets:[{data:d,backgroundColor:colors,borderRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#eef4f3'}},x:{grid:{display:false}}}}};else if(t==='line')cfg={type:'line',data:{labels:l,datasets:[{data:d,borderColor:'#0B8FAC',backgroundColor:'rgba(11,143,172,0.1)',fill:true,tension:.4,pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'#eef4f3'}},x:{grid:{display:false}}}}};else if(t==='donut')cfg={type:'doughnut',data:{labels:l,datasets:[{data:d,backgroundColor:colors,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'70%',plugins:{legend:{position:document.dir==='rtl'?'left':'right'}}}};new Chart(ctx,cfg);});}

function initInventorySteppers(){document.querySelectorAll('.ph-stepper').forEach(s=>{const i=s.querySelector('input'),dec=s.querySelector('.dec'),inc=s.querySelector('.inc');if(!i)return;const up=()=>{let v=parseInt(i.value)||0;if(v<0)v=0;i.value=v;const r=s.closest('[data-status]');if(!r)return;const m=parseInt(r.dataset.min||0);let st=v===0?'out':(v<=m?'low':'ok');r.dataset.status=st;const b=r.querySelector('.ph-badge');if(b){b.className='ph-badge '+st;b.innerHTML='<span></span>'+(st==='ok'?'متوفر':st==='low'?'منخفض':'نافذ');}};if(dec)dec.addEventListener('click',()=>{i.value=(parseInt(i.value)||0)-1;up();});if(inc)inc.addEventListener('click',()=>{i.value=(parseInt(i.value)||0)+1;up();});i.addEventListener('input',up);});}

function initFilterTabs(){document.querySelectorAll('[data-ph-tabs]').forEach(c=>{const t=c.dataset.phTabs,items=document.querySelectorAll(t+' [data-status]');c.querySelectorAll('.ph-tab').forEach(tab=>{tab.addEventListener('click',()=>{c.querySelectorAll('.ph-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const f=tab.dataset.filter;items.forEach(it=>it.style.display=(!f||f==='all'||it.dataset.status===f)?'':'none');});});});}

function initMedicineSearch(){const i=document.querySelector('[data-ph-search]');if(!i)return;const t=i.dataset.phSearch;i.addEventListener('input',()=>{const q=i.value.trim().toLowerCase();document.querySelectorAll(t).forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'':'none');});}

function initModals(){document.querySelectorAll('[data-ph-modal-open]').forEach(b=>b.addEventListener('click',()=>{const m=document.querySelector(b.dataset.phModalOpen);if(m)m.classList.add('active');}));document.querySelectorAll('[data-ph-modal-close]').forEach(b=>b.addEventListener('click',()=>{const m=document.querySelector(b.dataset.phModalClose);if(m)m.classList.remove('active');}));document.querySelectorAll('.ph-modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('active');}));}

function initMap(){const e=document.getElementById('pharmacyMap');if(!e||!window.L)return;const lat=parseFloat(e.dataset.lat)||15.3694,lng=parseFloat(e.dataset.lng)||44.1910,map=L.map(e).setView([lat,lng],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(map);const m=L.marker([lat,lng],{draggable:true}).addTo(map),la=document.getElementById('latitude'),ln=document.getElementById('longitude');m.on('dragend',()=>{const p=m.getLatLng();if(la)la.value=p.lat.toFixed(6);if(ln)ln.value=p.lng.toFixed(6);});map.on('click',ev=>{m.setLatLng(ev.latlng);if(la)la.value=ev.latlng.lat.toFixed(6);if(ln)ln.value=ev.latlng.lng.toFixed(6);});}